---
- name: Add docker repositories
  yum_repository:
    name: docker
    description: docker
    baseurl: https://download.docker.com/linux/centos/7/x86_x64/stable
    enabled: yes

- name: Add Docker GPG Key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

# - name: add docker-ce repo.
#   shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
#   args:
#     chdir: "/etc/yum.repos.d"
#     creates: docker-ce.repo

- name: Add Docker CE repo
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docker-ce.repo

- name: Update package lists
  yum:
    update_cache: yes

- name: Install docker engine
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Enable and Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: present

- name: docker python
  pip:
    name: docker-py
    executable: /usr/local/bin/pip3
    enabled: yes
